# Application Name
spring.application.name=hrm-system

# Server Port (Render automatically PORT env variable deta hai)
server.port=${PORT:8080}

# PostgreSQL Database Connection (Environment Variables se)
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

# Swagger/OpenAPI UI (Optional)
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Bean Definition Override Fix
spring.main.allow-bean-definition-overriding=true

# JWT Configuration (Environment Variable se - SECURITY KE LIYE ZAROORI)
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.jpa.open-in-view=false
spring.jackson.serialization.fail-on-empty-beans=false

# Logging (Production mein INFO rakhein, DEBUG nahi)
logging.level.com.example.hrm.system.security=INFO
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB