# Application Name
spring.application.name=hrm-system

# Server Port (optional, default is 8080)
server.port=8080

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/hrm_system
spring.datasource.username=postgres
spring.datasource.password=altaf
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Swagger/OpenAPI UI (Optional)
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ? ADD THIS LINE TO FIX THE ERROR ?
spring.main.allow-bean-definition-overriding=true
# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Logging
logging.level.com.example.hrm.system.security=DEBUG